### ISSUE TITLE
[12.0] Product Barcode inherit error

### ISSUE THREAD

**Issue by rowemoore** [CybroOdoo/CybroAddons#112]
There is no div with class 'col-4' in product.report_simple_label (odoo 12) 
so this: `<xpath expr="//div[hasclass('col-4')]" position="replace">`
needs to be  (for example) `<xpath expr="//div" position="replace">`

**Comment by CybroOdoo** [comment]
Hi,
Thank you for your information. 
The issue comes because of changes on odoo code. We have fixed the issue.
