### ISSUE TITLE
[12.0] salon_management - issue after installation

### ISSUE THREAD

**Issue by satriani-vai** [CybroOdoo/CybroAddons#113]
After fresch installation:
![image](https://user-images.githubusercontent.com/5981417/56455903-19f76080-6365-11e9-8f2d-2dd4a998b4a6.png)
After select Salon in menue:
![image](https://user-images.githubusercontent.com/5981417/56456095-d2be9f00-6367-11e9-9f89-841098756d99.png)
Here a log from Chromium:
[0.0.0.0-1555756166903.log](https://github.com/CybroOdoo/CybroAddons/files/3100018/0.0.0.0-1555756166903.log)

**Comment by CybroOdoo** [comment]
Hi,
We have fixed the issue.
Commit ref : d16e12d

**Comment by satriani-vai** [comment]
Unfortunately, no success with the bugfix
![image](https://user-images.githubusercontent.com/5981417/56818338-b929c580-6847-11e9-8edb-6083512b23fd.png)
