### ISSUE TITLE
V11: pos_mrp_order - create other production orders that you should not create

### ISSUE THREAD

**Issue by marionumza** [CybroOdoo/CybroAddons#117]
It turns out that I create a product with a list of materials and I frame it so that I can analyze the production by post.
However, when I select that product and then another product (which does not necessarily have the option of production marked by the pos), it sends me two orders for the production of the first product that I put in the cart

-----------------------------------------
Spanish

Resulta que creo un producto con lista de materiales y lo marco para que raealice la producción por el pos.
Sin embargo cuando selecciono ese producto y luego otro producto (que no necesariamente tiene marcada la opcion de producción por el pos), me lanza dos pedidos de producción del primer producto que puse en el carrito

![Screenshot_1](https://user-images.githubusercontent.com/19730236/57800044-c7705080-7726-11e9-84b4-76546ab947d2.png)
![Screenshot_2](https://user-images.githubusercontent.com/19730236/57800045-c7705080-7726-11e9-92b1-e64cb29e37ca.png)
![Screenshot_3](https://user-images.githubusercontent.com/19730236/57800046-c7705080-7726-11e9-9fbd-a4f710452805.png)
![Screenshot_4](https://user-images.githubusercontent.com/19730236/57800047-c808e700-7726-11e9-8588-5dbb4c42aaa7.png)
![Screenshot_5](https://user-images.githubusercontent.com/19730236/57800049-c808e700-7726-11e9-82f8-8429eeaa2269.png)

**Comment by CybroOdoo** [comment]
Hi,
The issue is fixed.
