### ISSUE TITLE
[11.0][inventory_barcode_scanning] odoo breaks after placing into folder

### ISSUE THREAD

**Issue by rogerv95** [CybroOdoo/CybroAddons#123]
Hello,
I've come to a weird situation. I had been previously able to use all the barcode related plugins with odoo without any problem. Since today, after updating ubuntu (not de distro, only a simple apt-get upgrade) odoo stopped working. I assume it's because the apt-get also updated odoo, and in the current version maybe there's something causing it to fail.

The tricky part is that odoo fails right away after placing the addon into the custom addons folder. After that images, icons and developer mode with assets stop working. I've checked all the logs, cleared caches, etc. But they don't show any error or anything suspicious. If I remove the folder from the custom addons it starts working completely normal again. 

I've checked if it's a problem with dependencies but it doesn't seem like it needs anything extra, and I was able to test all the addons previously in the last odoo update.

_Edit: Odoo version: Odoo 11.0-20190318 (Community Edition)_

**Comment by CybroOdoo** [comment]
Hi,
There is no such issue with this module.
Your updates will not affect this module, may be the issue is with your odoo.
Try the updated version of odoo.
