### ISSUE TITLE
[12.0] inventory_barcode_scanning

### ISSUE THREAD

**Issue by rodrig92** [CybroOdoo/CybroAddons#126]
Hello,

When I save the picking form all items are placed in quantity 0

I put a Gif with the example.

Thank you

![screen](https://user-images.githubusercontent.com/5502233/67553809-ef1c0980-f705-11e9-80e7-b2cd4083d54c.gif)

**Comment by CybroOdoo** [comment]
Hi,
The issue is fixed.

**Comment by rodrig92** [comment]
Hi,

The issue is not closed,

Now, if you want to read several items with the same barcode, it is impossible. The onchange function is not executed if the value does not change.

I'm trying to fix it. When I have the fix, what do you prefere? Do I copy and paste the code here or do I make a PR?

Regards
