### ISSUE TITLE
when Product is creating first time with variants its not generated bar-code V13 (missing first product barcode)

### ISSUE THREAD

**Issue by usmanfarzandali** [CybroOdoo/CybroAddons#131]
when i create product with variants its not generating barcode ...
barcode field is empty 
![Screenshot from 2019-12-20 10-49-14](https://user-images.githubusercontent.com/22232100/71338330-3fcaaa00-2571-11ea-8898-cfc01612ac42.png)
![Screenshot from 2019-12-20 10-50-15](https://user-images.githubusercontent.com/22232100/71338331-40634080-2571-11ea-8e08-fb6964a4ba44.png)

**Comment by CybroOdoo** [comment]
Hi
The issue is fixed.
