### ISSUE TITLE
xe_currency_converter legal issue

### ISSUE THREAD

**Issue by mohamedhagag** [CybroOdoo/CybroAddons#132]
https://github.com/CybroOdoo/CybroAddons/blob/c5478eefb72f8535b442773997b0d2dd0bfcb746/xe_currency_converter/models/config_settings.py#L3

as per xe service agreement, parsing of html output is prohibited, here's the warning inside the html output of the website:

> ***** FOR INFORMATION ON PARSING THIS DATA, REFER TO: https://www.xe.com/currencytables/parsehelp.htm *****

**Comment by CybroOdoo** [comment]
Hi
Thanks for reporting the issue.
We will look into it and fix as soon as possible.
