### ISSUE TITLE
No type field for sale order but used in action_confirm

### ISSUE THREAD

**Issue by tanzilkhan** [CybroOdoo/CybroAddons#136]
There is an error in this line -

https://github.com/CybroOdoo/CybroAddons/blob/13.0/base_accounting_kit/models/credit_limit.py#L82

There is no self.type field for sale.order . It gives an error. Shouldn't that be invoice_id field?

**Comment by CybroOdoo** [comment]
Hi,
Thanks for reporting the issue, we have fixed it.
