### ISSUE TITLE
[12.0] employee_documents_expiry: empty "Expiry Date"

### ISSUE THREAD

**Issue by abdallamohamedcore** [CybroOdoo/CybroAddons#138]
Hello
I have issue appeared when create document record without specify "Expiry Date" as below picture 

![image](https://user-images.githubusercontent.com/57271690/74746966-dca67c80-526e-11ea-89c3-6442815259d1.png)

**Comment by CybroOdoo** [comment]
Hi,
Thanks for reporting the issue,  we have fixed it , get the updated version from app store.
