### ISSUE TITLE
[13.0] Tax report not show 0% taxed moves

### ISSUE THREAD

**Issue by elperrofarelo** [CybroOdoo/CybroAddons#142]
The tax report doesn't show the moves with tax = 0 only bigger than 0
Please change the line 113 in /reports/report_tax.py from:
if tax['tax']:
to
if tax['net']:
then it will show the tax moves with positive "net" and 0 "tax"

**Comment by CybroOdoo** [comment]
Hi
Thanks for your suggestion, we will look into it and update.
