### ISSUE TITLE
[13.0] hr_payroll_data two deduction categories

### ISSUE THREAD

**Issue by elperrofarelo** [CybroOdoo/CybroAddons#143]
Two deduction categories with the same code in /hr_payroll_community/data/hr_payroll_data.xml:

       <record id="DED" model="hr.salary.rule.category">
            <field name="name">Deduction</field>
            <field name="code">DED</field>
        </record>
        <record id="DED" model="hr.salary.rule.category">
            <field name="name">Deduction</field>
            <field name="code">DED</field>
        </record>

Please remove one

**Comment by CybroOdoo** [comment]
Hi,
Thanks for your findings, we updated the code.
