### ISSUE TITLE
(13.0)Odoo Debranding error popup when switching languange

### ISSUE THREAD

**Issue by eversatis** [CybroOdoo/CybroAddons#148]
It works overall but the following error popup and flash away quickly every time when I switch language. I managed to copy the error message as bellow:

Error: Uncaught TypeError: Cannot read property 'then' of undefined http://47.94.90.3/web/content/511-b70e091/web.assets_common.js:925 Traceback: TypeError: Cannot read property 'then' of undefined at Class.start (http://47.94.90.3/web/content/622-48c8fb4/web.assets_backend.js:2821:257) at Class.start (http://47.94.90.3/web/content/511-b70e091/web.assets_common.js:3864:371) at HTMLDocument. (http://47.94.90.3/web?:70:40) at mightThrow (http://47.94.90.3/web/content/511-b70e091/web.assets_common.js:914:18) at process (http://47.94.90.3/web/content/511-b70e091/web.assets_common.js:916:89)

**Comment by CybroOdoo** [comment]
Hi
Are you using enterprise version ?

**Comment by eversatis** [comment]
Yes, you are right, I am using enterprise version, is it not supported? Thank you for your answer.

**Comment by CybroOdoo** [comment]
Hi,
Sorry currently it is not compatible with enterprise version. We are working on it.
Thanks
