### ISSUE TITLE
Confused license type used in product_combo_pack module

### ISSUE THREAD

**Issue by antherkiv** [CybroOdoo/CybroAddons#151]
Hi everyone specially @AjmalCybro, there are reference to LGLPv3 license in the readme inside the module, but appears it to use AGPL so I confused a lot.

It is posible to change it to LGPL v3 in manifest?

Hi, i'm sorry I'm not native speaker

**Comment by CybroOdoo** [comment]
Hi @antherkiv 
Thanks for reporting the conflict in the license.
We updated the both to AGPL V3.
