### ISSUE TITLE
Salon Management : error install on V9

### ISSUE THREAD

**Issue by mslokhat** [CybroOdoo/CybroAddons#16]
Hi,
got this error when triyng to install on v9c :

  File "/odoo/odoo-server/openerp/addons/base/ir/ir_model.py", line 991, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % (xmlid))
ParseError: "External ID not found in the system: website.website2_main_menu" while parsing /odoo/custom/addons/salon_management/views/salon_bookings.xml:4, near
<record id="website_menu_salon_booking" model="website.menu">
            <field name="name">Bookings</field>
            <field name="url">/page/salon_management.salon_booking_form</field>
            <field name="parent_id" ref="website.website2_main_menu"/>
            <field name="sequence" type="int">80</field>
            <field name="website_id" ref="website.website2"/>
        </record>

**Comment by CybroOdoo** [comment]
Hi,
Thanks for bug report.
We fixed and updated the module. Please check it now.
