### ISSUE TITLE
[14.0] employee_documents_expiry cannot create documents

### ISSUE THREAD

**Issue by evanrianto** [CybroOdoo/CybroAddons#162]
I just installted the employee_documents_expiry and cannot create a single document. It says Access Error 'Database fetch misses ids (('20',)) and has extra ids ((20,)), may be caused by a type incoherence in a previous request'.

![image](https://user-images.githubusercontent.com/38183317/109904803-5f5e7600-7cd0-11eb-9ffc-1b37e53616e2.png)

**Comment by CybroOdoo** [comment]
Hi
The issue is fixed.
