### ISSUE TITLE
[salon v9] : error/missing on approving a booking

### ISSUE THREAD

**Issue by mslokhat** [CybroOdoo/CybroAddons#17]
Hi,
added a booking on website, when approving the booking in back office : 
Server application error {"message":"Odoo Server Error","code":200,"data":{"debug":"Traceback (most recent call last):\n  File \"/odoo/odoo-server/openerp/http.py\", line 648, in _handle_exception\n    return super(JsonRequest, self)._handle_exception(exception)\n  File \"/odoo/odoo-server/openerp/http.py\", line 685, in dispatch\n    result = self._call_function(**self.params)\n  File \"/odoo/odoo-server/openerp/http.py\", line 321, in _call_function\n    return checked_call(self.db, *args, **kwargs)\n  File \"/odoo/odoo-server/openerp/service/model.py\", line 160, in wrapper\n    raise ValidationError(msg)\nValidationError: ('The operation cannot be completed, probably due to the following:\\n- deletion: you may be trying to delete a record while other records still reference it\\n- creation/update: a mandatory field is not correctly set\\n\\n[object with reference: salon.stages - salon.stages]', None)\n","exception_type":"validation_error","message":"The operation cannot be completed, probably due to the following:\n- deletion: you may be trying to delete a record while other records still reference it\n- creation/update: a mandatory field is not correctly set\n\n[object with reference: salon.stages - salon.stages]\nNone","name":"openerp.exceptions.ValidationError","arguments":["The operation cannot be completed, probably due to the following:\n- deletion: you may be trying to delete a record while other records still reference it\n- creation/update: a mandatory field is not correctly set\n\n[object with reference: salon.stages - salon.stages]",null]}}

**Comment by CybroOdoo** [comment]
Issue related to compatibility of browsers on front-end part of this addon.
