### ISSUE TITLE
[salon_management]  pls. v10.0

### ISSUE THREAD

**Issue by satriani-vai** [CybroOdoo/CybroAddons#20]
I would be very happy if you would update this great module to the version 10.0
Is it possible in this module to manage time of session / produkt? So you or customer know how long the chair is busy. And can the customer choose the employee?
Also, if you want I can halp you, to make this module multilingual. I can German and Russian :wink:

**Comment by CybroOdoo** [comment]
We will upgrade soon.
Managing time is already included.

**Comment by satriani-vai** [comment]
Thank you very much!
If you need a help for russian or german translation, so let me know ;)
