### ISSUE TITLE
Error in subscription module

### ISSUE THREAD

**Issue by vivoras** [CybroOdoo/CybroAddons#208]
I have the subscription module installed in odoo V15 (Docker) and when I create a quotation and click on the confirm button, the subscription is not automatically created. I don't see any errors and I don't know what else I should check

**Comment by ngalfas** [comment]
I installed subscription package on v16 and i have the same problem.  
I make draft subscriptions but no buttons appear to move to 'In progress' status.

![Image1](https://user-images.githubusercontent.com/22976096/226138632-36a8b455-7a96-4b90-9fdd-67c5a8ddbefa.png)
