### ISSUE TITLE
[14.0] [base_accounting_kit] Error multi-company account asset - Community Version

### ISSUE THREAD

**Issue by GuilhermeKimoto** [CybroOdoo/CybroAddons#215]
Hello Guys, I'm facing this error when trying to perform some actions on the asset, the multi-company field is set to true in the user.
![image](https://user-images.githubusercontent.com/70413601/194882693-a096ca49-6ded-4420-a3f6-196546b1d501.png)

works perfectly when I disable some registry rules, but I believe it is not the best way.
![image](https://user-images.githubusercontent.com/70413601/194882237-3aec6bd4-2632-4dc2-b3a9-8adde0144826.png)

Does anybody know how to solve this?

**Comment by ABMMK** [comment]
Did you get the solution for that?
