### ISSUE TITLE
inventory_report_generator  14.0.1.0.0

### ISSUE THREAD

**Issue by whotopia** [CybroOdoo/CybroAddons#223]
Installation of this module causes major issues for me with the list view types across the whole system. 
Before installing this module, my search dropdown in Partners e.g. looks like this:
![Screenshot 2022-11-12 at 14 22 57](https://user-images.githubusercontent.com/9039050/201476179-2a2d499a-f774-4821-849d-bea43aab4153.png)
whereas after installation of the addon, it looks like this:
![Screenshot 2022-11-12 at 14 24 23](https://user-images.githubusercontent.com/9039050/201476196-6be7b507-2863-4b5c-b189-e45eb97b7563.png)

This issue is seen on Odoo 14 Community edition. I have tried both the OCB and Odoo native versions.   It seems to be reproducible for me just by installing the addon.  However problem could be due to some interaction with another addon.  

There are really no errors associated with the installation nor any thing during runtime to point to this addon causing this problem.  It was thus quite frustrating for me to find this. (lots of addon de-installation and playing around).

Hopefully this can be fixed and this bug report helps someone.

**Comment by CybroOdoo** [comment]
Hi @whotopia 

Thank you for reporting the issue. We will check and update asap.

**Comment by CybroOdoo** [comment]
Hi @whotopia 

Can you please download the latest version of the module and try.
