### ISSUE TITLE
[9.0] Error on load POS pos_product_category_filter

### ISSUE THREAD

**Issue by mtbochaca** [CybroOdoo/CybroAddons#23]
When load de POS with module pos_product_category_filter, I have this error:

> _Cannot create property '0' on boolean 'false'
>     at Class.add_categories (http://192.168.1.55:8069/web/content/829-59e0d5f/point_of_sale.assets.js:373:107)
>     at Object.loaded (http://192.168.1.55:8069/web/content/829-59e0d5f/point_of_sale.assets.js:370:9)
>     at Object.<anonymous> (http://192.168.1.55:8069/web/content/829-59e0d5f/point_of_sale.assets.js:128:48)
>     at Object.<anonymous> (http://192.168.1.55:8069/web/content/246-83ab5b0/web.assets_common.js:650:681)
>     at fire (http://192.168.1.55:8069/web/content/246-83ab5b0/web.assets_common.js:644:299)
>     at Object.fireWith [as resolveWith] (http://192.168.1.55:8069/web/content/246-83ab5b0/web.assets_common.js:649:198)
>     at Object.<anonymous> (http://192.168.1.55:8069/web/content/246-83ab5b0/web.assets_common.js:650:874)
>     at fire (http://192.168.1.55:8069/web/content/246-83ab5b0/web.assets_common.js:644:299)
>     at Object.fireWith [as resolveWith] (http://192.168.1.55:8069/web/content/246-83ab5b0/web.assets_common.js:649:198)
>     at Object.deferred.(anonymous function) (http://192.168.1.55:8069/web/content/246-83ab5b0/web.assets_common.js:651:56)_

I solved the error modifying the file /static/src/js/category.js on line 48:

               `     categories[i].parent_id[0] = 0;`

for this code:

```
 for(var i=0, len = categories.length; i < len; i++){
                if(categories[i].available === true){
                    categories[i].parent_id = 0;
                }
```

**Comment by CybroOdoo** [comment]
We updated the code. Thanks for your feedback and suggestions.
