### ISSUE TITLE
Uncaught TypeError: Cannot read property 'raw_value' of undefined in project_subtask

### ISSUE THREAD

**Issue by tanzilkhan** [CybroOdoo/CybroAddons#25]
I installed your module and found this error when clicked on sub-tasks menu:

_Uncaught TypeError: Cannot read property 'raw_value' of undefined_

After some investigation, I found there is no 'remaining_hours' field in the project.sub_task table. But it was declared in kanban view of subtask.

https://github.com/CybroOdoo/CybroAddons/blob/10.0/project_subtask/views/sub_task.xml#L96-L101

After commenting out this the Sub-task view worked.

**Comment by CybroOdoo** [comment]
Thanks for notifying us.
We changed the code and fixed the issue.
