### ISSUE TITLE
[8.0] Fail to print project_status_level_report 

### ISSUE THREAD

**Issue by syci** [CybroOdoo/CybroAddons#26]
When I try to print the report, the following error occurs:

> except_orm: (u'Required report does not exist: project_status_report', (<type 'exceptions.Exception'>, Exception(u'Required report does not exist: project_status_report',), <traceback object at 0x7fb9ed3ceb00>))

**Comment by CybroOdoo** [comment]
We tested it again, And we can't recreate the reported issue. Please check the same in a fresh DB.
Thanks
