### ISSUE TITLE
[10.0] salon_management need more types of chairs or seats

### ISSUE THREAD

**Issue by satriani-vai** [CybroOdoo/CybroAddons#27]
The beauty salon have specific types of chairs or seats for the each service.
e.g manicure needs a table (there is 3 tables in beauty salon), pedicure needs a chair (there is 4 chairs in beauty salon) and cosmetics or massage needs a beauty bed/massage table (there is only one in beauty salon)
So, we have an issue with the booking. How to solve this issue?
Many thanks for this module and best regards.

**Comment by CybroOdoo** [comment]
Thanks for your suggestion.

To solve this issue, We have to do some customisation on this application.
Feel free to contact us on our skype id 'cybrosystech'
