### ISSUE TITLE
Error installing sales_team_parent module

### ISSUE THREAD

**Issue by David-II** [CybroOdoo/CybroAddons#28]
Error is founded when trying to install the module **sales_team_parent**:

```
2017-08-07 17:50:40,536 1 INFO mydb odoo.addons.base.ir.ir_translation: module sale_operating_unit: no translation for language es
2017-08-07 17:50:40,924 1 INFO mydb odoo.modules.registry: module sales_team_parent: creating or updating database tables
2017-08-07 17:50:41,072 1 INFO mydb odoo.models: Storing computed values of crm.team fields currency_id
2017-08-07 17:50:41,100 1 INFO mydb odoo.sql_db: bad query: UPDATE "crm_team" SET "currency_id"=NULL,"write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (1, 2)
2017-08-07 17:50:41,100 1 ERROR mydb odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 136, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/usr/lib/python2.7/dist-packages/odoo/modules/registry.py", line 327, in init_models
    models[0].recompute()
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 5292, in recompute
    recs.browse(ids)._write(dict(vals))
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 3631, in _write
    cr.execute(query, params + (sub_ids,))
  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
IntegrityError: null value in column "currency_id" violates not-null constraint
DETAIL:  Failing row contains (2, 2017-07-30 23:05:32.135666, null, 1, 1, null, null, null, 2017-08-07 17:50:41.073208, t, Website Sales, null, t, null, null, 3, null, t, null, 1, sale, null, null).
```

The database has many modules installed, but has not been used, so almost no data inside the db.
List of installed modules:
> Nombre de módulo | Nombre técnico | Autor | Última versión | Estado
> -- | -- | -- | -- | --
> Invoicing | account | Odoo S.A. | 10.0.1.1 | Instalado
> Accounting and Finance | account_accountant | Odoo S.A. | 10.0.1.1 | Instalado
> Account Analytic Defaults | account_analytic_default | Odoo S.A. | 10.0.1.0 | Instalado
> Assets Management | account_asset | Odoo S.A. | 10.0.1.0 | Instalado
> Account Banking Mandate | account_banking_mandate | Compassion CH, Tecnativa, Akretion, Odoo Community Association (OCA) | 10.0.1.1.0 | Instalado
> Account Banking Mandate Sale | account_banking_mandate_sale | Akretion, Odoo Community Association (OCA) | 10.0.1.0.0 | Instalado
> Account Banking PAIN Base Module | account_banking_pain_base | Akretion, Noviat, Tecnativa, Odoo Community Association (OCA) | 10.0.1.0.0 | Instalado
> Account Banking SEPA Credit Transfer | account_banking_sepa_credit_transfer | Akretion, Tecnativa, Odoo Community Association (OCA) | 10.0.1.0.0 | Instalado
> Account Banking SEPA Direct Debit | account_banking_sepa_direct_debit | Akretion, Tecnativa, Odoo Community Association (OCA) | 10.0.1.0.0 | Instalado
> Account Bank Statement Import | account_bank_statement_import | Odoo S.A. | 10.0.1.0 | Instalado
> Import CSV Bank Statement | account_bank_statement_import_csv | Odoo S.A. | 10.0.1.0 | Instalado
> Import OFX Bank Statement | account_bank_statement_import_ofx | Odoo SA,Akretion,La Louve,GRAP,Odoo Community Association (OCA) | 10.0.1.0.0 | Instalado
> Import QIF Bank Statements | account_bank_statement_import_qif | OpenERP SA,Tecnativa,Odoo Community Association (OCA) | 10.0.1.0.0 | Instalado
> Budgets Management | account_budget | Odoo S.A. | 10.0.1.0 | Instalado
> Cancel Journal Entries | account_cancel | Odoo S.A. | 10.0.1.1 | Instalado
> Check Printing Base | account_check_printing | Odoo S.A. | 10.0.1.0 | Instalado
> Account Extension | account_extension | Odoo S.A. | 10.0.1.0 | Instalado
> Account Fiscal Year | account_fiscal_year | Camptocamp SA,Odoo Community Association (OCA) | 10.0.1.0.0 | Instalado
> account_online_sync | account_online_sync | Odoo S.A. | 10.0.2.0 | Instalado
> Accounting with Operating Units | account_operating_unit | Eficent, Serpent Consulting Services Pvt. Ltd.,Odoo Community Association (OCA) | 10.0.1.0.0 | Instalado
> Account Payment Mode | account_payment_mode | Akretion,Odoo Community Association (OCA) | 10.0.1.0.0 | Instalado
> Account Payment Order | account_payment_order | ACSONE SA/NV, Therp BV, Tecnativa, Akretion, Odoo Community Association (OCA) | 10.0.1.2.0 | Instalado
> Account Payment Partner | account_payment_partner | Akretion, Tecnativa, Odoo Community Association (OCA) | 10.0.1.1.0 | Instalado
> Account Payment Sale | account_payment_sale | Akretion, Tecnativa, Odoo Community Association (OCA) | 10.0.1.0.0 | Instalado
> Payment Term Extension | account_payment_term_extension | Camptocamp,Tecnativa,Odoo Community Association (OCA) | 10.0.1.0.0 | Instalado
> Accounting Reports | account_reports | Odoo S.A. | 10.0.1.0 | Instalado
> Payment Follow-up Management | account_reports_followup | Odoo S.A. | 10.0.1.0 | Instalado
> Tax Balance | account_tax_balance | Agile Business Group, Therp BV, Tecnativa, ACSONE SA/NV, Odoo Community Association (OCA) | 10.0.1.1.0 | Instalado
> Accounting Consistency Tests | account_test | Odoo S.A. | 10.0.1.0 | Instalado
> Account Types Menu | account_type_menu | Akretion,Odoo Community Association (OCA) | 10.0.1.0.0 | Instalado
> Yodlee | account_yodlee | Odoo S.A. | 10.0.2.0 | Instalado
> Analytic Accounting | analytic | Odoo S.A. | 10.0.1.1 | Instalado
> Analytic Operating Unit | analytic_operating_unit | Eficent, Odoo Community Association (OCA) | 10.0.1.0.0 | Instalado
> Password Encryption | auth_crypt | ['Odoo SA', 'FS3'] | 10.0.2.0 | Instalado
> OAuth2 Authentication | auth_oauth | Odoo S.A. | 10.0.1.0 | Instalado
> Signup | auth_signup | Odoo S.A. | 10.0.1.0 | Instalado
> Barcodes | barcodes | Odoo S.A. | 10.0.2.0 | Instalado
> Base | base | Odoo S.A. | 10.0.1.3 | Instalado
> Automated Action Rules | base_action_rule | Odoo S.A. | 10.0.1.0 | Instalado
> IBAN Bank Accounts | base_iban | Odoo S.A. | 10.0.1.0 | Instalado
> Base import | base_import | Odoo S.A. | 10.0.1.0 | Instalado
> Location management (aka Better ZIP) | base_location | Camptocamp,ACYSOS S.L.,Alejandro Santana,Tecnativa,Odoo Community Association (OCA) | 10.0.1.0.1 | Instalado
> Base Location Geonames Import | base_location_geonames_import | Akretion,Agile Business Group,Antiun Ingeniería S.L.,Tecnativa,Odoo Community Association (OCA) | 10.0.1.0.1 | Instalado
> Initial Setup Tools | base_setup | Odoo S.A. | 10.0.1.0 | Instalado
> VAT Number Validation | base_vat | Odoo S.A. | 10.0.1.0 | Instalado
> Dashboards | board | Odoo S.A. | 10.0.1.0 | Instalado
> IM Bus | bus | Odoo S.A. | 10.0.1.0 | Instalado
> Calendar | calendar | Odoo S.A. | 10.0.1.0 | Instalado
> Contacts Directory | contacts | Odoo S.A. | 10.0.1.0 | Instalado
> CRM | crm | Odoo S.A. | 10.0.1.0 | Instalado
> Operating Unit in CRM | crm_operating_unit | Eficent, Serpent Consulting Services Pvt. Ltd.,Odoo Community Association (OCA) | 10.0.1.0.0 | Instalado
> Live Currency Exchange Rate | currency_rate_live | Odoo S.A. | 10.0.1.0 | Instalado
> Date Range | date_range | ACSONE SA/NV, Odoo Community Association (OCA) | 10.0.1.0.1 | Instalado
> Decimal Precision Configuration | decimal_precision | Odoo S.A. | 10.0.0.1 | Instalado
> Delivery Costs | delivery | Odoo S.A. | 10.0.1.0 | Instalado
> Attachments List and Document Indexation | document | Odoo S.A. | 10.0.2.1 | Instalado
> Document Page | document_page | OpenERP SA, Odoo Community Association (OCA) | 10.0.1.0.0 | Instalado
> Document Page Approval | document_page_approval | Savoir-faire Linux, Odoo Community Association (OCA) | 10.0.1.0.0 | Instalado
> Environmental Aspects | document_page_environmental_aspect | Savoir-faire Linux, Odoo Community Association (OCA) | 10.0.1.0.0 | Instalado
> Document Management - Wiki - Environment Manual | document_page_environment_manual | Savoir-faire Linux,Odoo Community Association (OCA) | 10.0.1.0.0 | Instalado
> Health and Safety Manual | document_page_health_safety_manual | Savoir-faire Linux, Odoo Community Association (OCA) | 10.0.1.0.0 | Instalado
> Document Management - Wiki - Procedures | document_page_procedure | Savoir-faire Linux,Odoo Community Association (OCA) | 10.0.1.0.0 | Instalado
> Quality Manual | document_page_quality_manual | OpenERP SA, Odoo Community Association (OCA) | 10.0.1.0.0 | Instalado
> Document Management - Wiki - Work Instructions | document_page_work_instruction | Savoir-faire Linux,Odoo Community Association (OCA) | 10.0.1.0.0 | Instalado
> Employees From User | employee_creation_from_user | Cybrosys Techno Solutions | 10.0.1.0.0 | Instalado
> Email Gateway | fetchmail | Odoo S.A. | 10.0.1.0 | Instalado
> Grid View | grid | Odoo S.A. | 10.0.0.1 | Instalado
> Employee Directory | hr | Odoo S.A. | 10.0.1.1 | Instalado
> Attendances | hr_attendance | Odoo S.A. | 10.0.2.0 | Instalado
> Employee Contracts | hr_contract | Odoo S.A. | 10.0.1.0 | Instalado
> Leave Management | hr_holidays | Odoo S.A. | 10.0.1.5 | Instalado
> Holidays expiration | hr_holidays_expiration | Onestein | 10.0.1.0.0 | Instalado
> Leaves Gantt | hr_holidays_gantt | Odoo S.A. | 10.0.1.0 | Instalado
> HR Public Holidays | hr_public_holidays | Michael Telahun Makonnen <mmakonnen@gmail.com>, Odoo Community Association (OCA) | 10.0.1.0.0 | Instalado
> Recruitment Process | hr_recruitment | Odoo S.A. | 10.0.1.0 | Instalado
> Hr Recruitment Interview Forms | hr_recruitment_survey | Odoo S.A. | 10.0.1.0 | Instalado
> Advanced HR Recruitment | hr_recruitment_validations | Cybrosys Techno Solutions | 10.0.1.0.0 | Instalado
> Timesheets | hr_timesheet | Odoo S.A. | 10.0.1.0 | Instalado
> ESC/POS Hardware Driver | hw_escpos | Odoo S.A. | 10.0.1.0 | Instalado
> Hardware Proxy | hw_proxy | Odoo S.A. | 10.0.1.0 | Instalado
> Knowledge Management System | knowledge | OpenERP SA, MONK Software, Odoo Community Association (OCA) | 10.0.1.0.0 | Instalado
> Spain - Accounting (PGCE 2008) | l10n_es | Spanish Localization Team | 10.0.4.0 | Instalado
> Gestión de activos fijos para España | l10n_es_account_asset | Serv. Tecnol. Avanzados - Pedro M. Baeza, Odoo Community Association (OCA) | 10.0.8.0.2.0.0 | Instalado
> Account Banking Sepa - FSDD (Anticipos de crédito) | l10n_es_account_banking_sepa_fsdd | Comunitea,Odoo Community Association (OCA) | 10.0.8.0.1.0.0 | Instalado
> Importación de extractos bancarios españoles (Norma 43) | l10n_es_account_bank_statement_import_n43 | Spanish Localization Team,Tecnativa,Odoo Community Association (OCA) | 10.0.1.1.0 | Instalado
> AEAT Base | l10n_es_aeat | Pexego,Serv. Tecnol. Avanzados - Pedro M. Baeza,AvanzOSC,Odoo Community Association (OCA) | 10.0.8.0.1.9.0 | Instalado
> AEAT modelo 111 | l10n_es_aeat_mod111 | AvanzOSC,Serv. Tecnol. Avanzados - Pedro M. Baeza,Antiun Ingeniería S.L.,MálagaTIC,G. Vermon,Odoo Community Association (OCA) | 10.0.8.0.2.0.0 | Instalado
> AEAT modelo 303 | l10n_es_aeat_mod303 | Guadaltech,AvanzOSC,Serv. Tecnol. Avanzados - Pedro M. Baeza,Antiun Ingeniería S.L.,Comunitea,Odoo Community Association (OCA) | 10.0.8.0.1.6.0 | Instalado
> Categorías de empresa CNAE 2009 | l10n_es_cnae | Tecnativa, Odoo Community Association (OCA) | 10.0.0.1 | Instalado
> Adaptación de los clientes, proveedores y bancos para España | l10n_es_partner | ZikZak,Acysos,Tecnativa,Odoo Community Association (OCA) | 10.0.1.0.0 | Instalado
> Topónimos españoles | l10n_es_toponyms | Spanish Localization Team, ZikZakMedia, Tecnativa, Odoo Community Association (OCA) | 10.0.1.0.0 | Instalado
> European NACE partner categories | l10n_eu_nace | Numérigraphe SARL,Sistheo,Odoo Community Association (OCA) | 10.0.1.0.0 | Instalado
> Link Tracker | link_tracker | Odoo S.A. | 10.0.1.0 | Instalado
> User Log Details | login_user_detail | Cybrosys Techno Solutions | 10.0.1.0.0 | Instalado
> Discuss | mail | Odoo S.A. | 10.0.1.0 | Instalado
> Firebase Cloud Messaging | mail_push | Odoo S.A. | 10.0.1.0 | Instalado
> Equipments | maintenance | Odoo S.A. | 10.0.1.0 | Instalado
> Marketing Campaigns | marketing_campaign | Odoo S.A. | 10.0.1.1 | Instalado
> Mass Mailing Campaigns | mass_mailing | Odoo S.A. | 10.0.2.0 | Instalado
> Mass Mailing Themes | mass_mailing_themes | Odoo S.A. | 10.0.1.0 | Instalado
> Management System | mgmtsystem | Savoir-faire Linux,Odoo Community Association (OCA) | 10.0.1.0.0 | Instalado
> Management System - Action | mgmtsystem_action | Savoir-faire Linux,Odoo Community Association (OCA) | 10.0.1.0.0 | Instalado
> Management System - Manual | mgmtsystem_manual | Savoir-faire Linux,Odoo Community Association (OCA) | 10.0.1.0.0 | Instalado
> Management System - Nonconformity | mgmtsystem_nonconformity | Savoir-faire Linux,Odoo Community Association (OCA) | 10.0.1.0.0 | Instalado
> Management System - Survey | mgmtsystem_survey | Savoir-faire Linux,Odoo Community Association (OCA) | 10.0.1.0.0 | Instalado
> Manufacturing | mrp | Odoo S.A. | 10.0.2.0 | Instalado
> Accounting - MRP | mrp_account | Odoo S.A. | 10.0.1.0 | Instalado
> Maintenance - MRP | mrp_maintenance | Odoo S.A. | 10.0.1.0 | Instalado
> Mrp Workorder | mrp_workorder | Odoo S.A. | 10.0.1.0 | Instalado
> Productivity | note | Odoo S.A. | 10.0.1.0 | Instalado
> Memos pad | note_pad | Odoo S.A. | 10.0.0.1 | Instalado
> Operating Unit | operating_unit | Eficent, Serpent Consulting Services Pvt. Ltd.,Odoo Community Association (OCA) | 10.0.1.0.0 | Instalado
> Collaborative Pads | pad | Odoo S.A. | 10.0.2.0 | Instalado
> Pad on tasks | pad_project | Odoo S.A. | 10.0.1.0 | Instalado
> Partner Survey | partner_survey | Tecnativa, Camptocamp, Odoo Community Association (OCA) | 10.0.1.0.0 | Instalado
> Payment Acquirer | payment | Odoo S.A. | 10.0.1.0 | Instalado
> Paypal Payment Acquirer | payment_paypal | Odoo S.A. | 10.0.1.0 | Instalado
> Transfer Payment Acquirer | payment_transfer | Odoo S.A. | 10.0.1.0 | Instalado
> Portal | portal | Odoo S.A. | 10.0.1.0 | Instalado
> Portal Sale | portal_sale | Odoo S.A. | 10.0.0.1 | Instalado
> Portal Stock | portal_stock | Odoo S.A. | 10.0.0.1 | Instalado
> Procurements | procurement | Odoo S.A. | 10.0.1.0 | Instalado
> Just In Time Scheduling | procurement_jit | Odoo S.A. | 10.0.1.0 | Instalado
> Products & Pricelists | product | Odoo S.A. | 10.0.1.2 | Instalado
> Products Expiration Date | product_expiry | Odoo S.A. | 10.0.1.0 | Instalado
> Project | project | Odoo S.A. | 10.0.1.1 | Instalado
> Project Code In Task | project_code_in_task | Cybrosys Techno Solutions | 10.0.1.0.0 | Instalado
> Project Forecast | project_forecast | Odoo S.A. | 10.0.1.0 | Instalado
> Forecast Grid View | project_forecast_grid | Odoo S.A. | 10.0.1.0 | Instalado
> Link module between project_forecast and sale(_timesheet) | project_forecast_sale | Odoo S.A. | 10.0.0.1 | Instalado
> Lifeline for Task | project_lifeline | Cybrosys Techno Solutions | 10.0.1.0.0 | Instalado
> Sub Tasks in Project | project_subtask | Cybrosys Techno Solutions | 10.0.2.0.0 | Instalado
> Project - Set Team and members | project_team | Serpent Consulting Services Pvt. Ltd. | 10.0.1.0.0 | Instalado
> Purchase Management | purchase | Odoo S.A. | 10.0.1.2 | Instalado
> Purchase and MRP Management | purchase_mrp | Odoo S.A. | 10.0.1.0 | Instalado
> Quotation Revised History | quotation_handler | Cybrosys Techno Solutions | 10.0.1.0.0 | Instalado
> Customer Rating | rating | Odoo S.A. | 10.0.1.0 | Instalado
> Report | report | Odoo S.A. | 10.0.1.0 | Instalado
> Intrastat Reporting | report_intrastat | Odoo S.A. | 10.0.1.0 | Instalado
> Base report xlsx | report_xlsx | Cybrosys Techno Solutions | 10.0.0.2 | Instalado
> Resource | resource | Odoo S.A. | 10.0.1.1 | Instalado
> Sales | sale | Odoo S.A. | 10.0.1.0 | Instalado
> Sale Cancel Reason | sale_cancel_reason | Camptocamp,Odoo Community Association (OCA) | 10.0.1.0.0 | Instalado
> Subscription Management (without frontend) | sale_contract | Camptocamp / Odoo | 10.0.1.1 | Instalado
> Deferred revenue management for contracts | sale_contract_asset | Odoo S.A. | 10.0.1.0 | Instalado
> Opportunity to Quotation | sale_crm | Odoo S.A. | 10.0.1.0 | Instalado
> Sales and MRP Management | sale_mrp | Odoo S.A. | 10.0.1.0 | Instalado
> Operating Unit in Sales | sale_operating_unit | Eficent, Serpent Consulting Services Pvt. Ltd.,Odoo Community Association (OCA) | 10.0.1.0.0 | Instalado
> Dates on Sales Order | sale_order_dates | Odoo S.A. | 10.0.1.1 | Instalado
> Sales Teams | sales_team | Odoo S.A. | 10.0.1.0 | Instalado
> Sales Team Operating Unit | sales_team_operating_unit | Eficent, SerpentCS,Odoo Community Association (OCA) | 10.0.1.0.0 | Instalado
> Sales and Warehouse Management | sale_stock | Odoo S.A. | 10.0.1.0 | Instalado
> Sales Timesheet | sale_timesheet | Odoo S.A. | 10.0.1.0 | Instalado
> Inventory Management | stock | Odoo S.A. | 10.0.1.1 | Instalado
> WMS Accounting | stock_account | Odoo S.A. | 10.0.1.1 | Instalado
> Warehouse Management Barcode Scanning | stock_barcode | Odoo S.A. | 10.0.1.0 | Instalado
> Stock Barcode in Mobile | stock_barcode_mobile | Odoo S.A. | 10.0.1.0 | Instalado
> Drop Shipping | stock_dropshipping | Odoo S.A. | 10.0.1.0 | Instalado
> Survey | survey | Odoo S.A. | 10.0.2.0 | Instalado
> Grid View for Timesheets | timesheet_grid | Odoo S.A. | 10.0.0.1 | Instalado
> Sales Timesheet: Grid Support | timesheet_grid_sale | Odoo S.A. | 10.0.0.1 | Instalado
> TMC API REST | tmc_api_rest | TMC Spain | 10.0.0.1 | Instalado
> User From Employee | user_creation_from_employee | Cybrosys Techno Solutions | 10.0.2.0.0 | Instalado
> UTM Trackers | utm | Odoo S.A. | 10.0.1.0 | Instalado
> Web | web | Odoo S.A. | 10.0.1.0 | Instalado
> Web Calendar | web_calendar | Odoo SA, Valentino Lab (Kalysto) | 10.0.2.0 | Instalado
> Odoo Web Diagram | web_diagram | Odoo S.A. | 10.0.2.0 | Instalado
> Web Editor | web_editor | Odoo S.A. | 10.0.1.0 | Instalado
> Web Enterprise | web_enterprise | Odoo S.A. | 10.0.1.0 | Instalado
> Web Gantt | web_gantt | Odoo S.A. | 10.0.2.0 | Instalado
> Base Kanban | web_kanban | Odoo S.A. | 10.0.2.0 | Instalado
> Gauge Widget for Kanban | web_kanban_gauge | Odoo S.A. | 10.0.1.0 | Instalado
> Mobile | web_mobile | Odoo S.A. | 10.0.1.0 | Instalado
> Planner | web_planner | Odoo S.A. | 10.0.1.0 | Instalado
> Odoo Settings Dashboard | web_settings_dashboard | Odoo S.A. | 10.0.1.0 | Instalado
> Website Builder | website | Odoo S.A. | 10.0.1.0 | Instalado
> Website Enterprise | website_enterprise | Odoo S.A. | 10.0.1.0 | Instalado
> Generic Form Controller | website_form | Odoo S.A. | 10.0.1.0 | Instalado
> Website Link Tracker | website_links | Odoo S.A. | 10.0.1.0 | Instalado
> Website Mail | website_mail | Odoo S.A. | 10.0.0.1 | Instalado
> Website Mass Mailing Campaigns | website_mass_mailing | Odoo S.A. | 10.0.1.0 | Instalado
> Website Partner | website_partner | Odoo S.A. | 10.0.0.1 | Instalado
> Payment: Website Integration | website_payment | Odoo S.A. | 10.0.1.0 | Instalado
> Website Portal | website_portal | Odoo S.A. | 10.0.1.0 | Instalado
> Website Portal for Sales | website_portal_sale | Odoo S.A. | 10.0.1.0 | Instalado
> Website Project | website_project | Odoo S.A. | 10.0.1.0 | Instalado
> Timesheet in Website Portal | website_project_timesheet | Odoo S.A. | 10.0.1.0 | Instalado
> Website Theme Install | website_theme_install | Odoo S.A. | 10.0.1.0 | Instalado
> Tours | web_tour | Odoo S.A. | 10.0.0.1 | Instalado
> Workload In Project | workload_in_project | Cybrosys Techno Solutions | 10.0.1.0.0 | Instalado

**Comment by CybroOdoo** [comment]
The problem was with the currency_id field. It was set to mandatory in this module. When we try to install this module in a database with demo data where there are some records with currency_id is null, It will raise this error. It will work when you try the same once again.

Anyway, We updated the code and this error fixed in git and odoo apps.
