### ISSUE TITLE
[Odoo 10.0] website_product_attachments - related documents not appear

### ISSUE THREAD

**Issue by arafatx** [CybroOdoo/CybroAddons#31]
After installed the website_product_attachments, and I added some attachments in the product inventory, when viewing the product from website I see no related documents that can be downloaded.

**Comment by CybroOdoo** [comment]
The module is still working for us. You may be using any other custom modules along with this. I that case, we cannot assure the working of the module. It will be better if you can give the feedback by testing the module with an untouched Odoo.

Thanks for reaching out.

**Comment by chepoez** [comment]
Hi, I just intalled the invoice_stock_move for odoo 10 and even though I see the Receive button on the vendors bill, the products are not moved to the inventory...
My product is configured to be a stockable product by the way.
Any advise on how to make it work?
![image](https://user-images.githubusercontent.com/10442961/38514919-2520f8a8-3bf8-11e8-807b-500556de48f1.png)
Thanks and best regards

in the installation I manually installed the following three extra modules
![image](https://user-images.githubusercontent.com/10442961/38515066-ae73f132-3bf8-11e8-96be-6e973904b106.png)
