### ISSUE TITLE
[odoo 10.0c] pos_product_creation got error when creating product

### ISSUE THREAD

**Issue by arafatx** [CybroOdoo/CybroAddons#37]
Step to reproduce:

1) Create a product from POS.
2) An error occur

Screenshot:

[<a href="https://imgbb.com/"><img src="https://image.ibb.co/dwU2GG/pos.png" alt="pos" border="0"></a>](url)

Product got created just the error appear.

**Comment by CybroOdoo** [comment]
We did several testing here on our end. We couldn't reproduce this type error.
It will be great if you can provide some more data like environment, os etc. And please update the feedback on fresh database pos system.
