### ISSUE TITLE
Order reprint pos not loading (black screen)

### ISSUE THREAD

**Issue by Ark74** [CybroOdoo/CybroAddons#38]
Hi!

I'm testing the module order_reprinting_pos on Odoo 10 CE, and I'm getting no screen after loading the POS.
The only customization that I can think of is the ticket done to the xml file.

Aside from that there is nothing different from the core code.

Seems like it's a common case, do you have the same issue?

**Comment by CybroOdoo** [comment]
We checked here and it is working perfectly. If you are facing issue in your end, Please try with a fresh DB and let us know.

**Comment by Ark74** [comment]
Hi! 
Seems the error was because of another plugin/addon on the POS.

I'd like to ask.
Does the plugin tries to load every order in the POS history?
I was testing a DB with ~4000 orders, and it takes a long time to load, and finally it will load only a few orders (~400) maybe because of memory saturation (my guess).

I'll have a look at this, maybe only load the orders in the current session could be a better approach, since loading every order on the POS screen it's not very effective on large databases.

Thanks for the suggestion.

**Comment by CybroOdoo** [comment]
It will take all orders as you pointed above. If you need to alter its data fetching, We can customize it.
