### ISSUE TITLE
round_off_invoices addon for Foreign Currency Invoice

### ISSUE THREAD

**Issue by jpcass** [CybroOdoo/CybroAddons#41]
Using the round_off_invoices addon, when validating the invoice in foreign currency the error attached appears.

[Foreign Currency Invoice.txt](https://github.com/CybroOdoo/CybroAddons/files/1478794/Foreign.Currency.Invoice.txt)

Regards

**Comment by CybroOdoo** [comment]
Fixed and Updated the module.
