### ISSUE TITLE
[Odoo 10] Error when i try to generate a lot of payslip

### ISSUE THREAD

**Issue by zaza121** [CybroOdoo/CybroAddons#44]
Hi, when i try to generate a lot of payslip for more than one employee i have this error: 

**ValueError: Expected singleton: hr.payslip(82, 83, 84, 85)**

This error come from these lines

https://github.com/CybroOdoo/CybroAddons/blob/05a06fbc19a0d94ce7c4b2c2b744d7d8e77662d1/payroll_timesheet/models/models.py#L124-L125

**Comment by hilarak** [comment]
this can solve by adding the following code on the same line
```
for record in self:
    timesheet_hours = record.timesheet_hours
    total_hours = record.total_hours 
```
