### ISSUE TITLE
About Porting for Odoo v10

### ISSUE THREAD

**Issue by satriani-vai** [CybroOdoo/CybroAddons#5]
Will you port the module to the version 10?
Thanks in advance.

**Comment by CybroOdoo** [comment]
Sorry For that. We were extremely busy with ongoing projects. Will update the modules soon. May I know, which module you are looking for urgently?

**Comment by satriani-vai** [comment]
Oh sorry, I mean salon_operation :blush:

**Comment by CybroOdoo** [comment]
Thank You
We will do it as soon as possible
