### ISSUE TITLE
issues in "Quality Assurance" module

### ISSUE THREAD

**Issue by ccandito** [CybroOdoo/CybroAddons#58]
Dear All,
I've appreciated a lot this module concept.
Just two remarks:
1) for some operation types works perfectly (e.g. receipts), for some others doesn't (e.g. internal transfer); please suggest what I did wrong
2) in case quality test has failed, what we should do for going on?

thanks in advance
Claudio Candito

**Comment by CybroOdoo** [comment]
As you know QC is a wide area. The module is just the basics. We know there are many things missing. We will try to fill the gaps as soon as possible.

   Regarding the pointed issues,
All operation types except Manufacturing works perfectly for us. and there is no special configuration required. Please let us know how we can regenerate the problem.
If the quality test is failed, the user cannot process that transaction. that is the current behaviour.

**Comment by ccandito** [comment]
Dear All,
Please find attached a screenshot related to the three test cases I did.
![screenshot from 2018-03-05 19-40-44](https://user-images.githubusercontent.com/8027589/36993162-5e857fc6-20ad-11e8-91ff-ce1b6a6aea06.png)
The "Receipts" Operation Type has been working out only. 
Please take into account the "delivery one" is Odoo standard, instead the "Receipt for production" is a custom one to manage goods receipts from a manufacturing order.
Regards
thanks in advance
claudio

**Comment by ccandito** [comment]
Dear All,
about the improvement of failed quality test case, I'd suggest as follows:
1) it is not allowed to delete test directly from the picking goods movement, but only from the quality management menù
2) product quantity has to be entered in quality test; for example for a goods movement of 100 pcs,  97 are passed and 3 are failed
3) for the 3 pcs which the quality test has failed for, an automatic goods movement has to be performed to move them in a "Quality Assurance" location.
Regards
Thanks in advance
Claudio
