### ISSUE TITLE
POS Product loading

### ISSUE THREAD

**Issue by taherg786** [CybroOdoo/CybroAddons#6]
The module surely displays the products whose categories have been mentioned, but the POS loads all the products at once.
This means it takes time to load 100,000 products, even if displayed/selected products are only 100.
(in my case, I have a relatively huge database)

**Comment by CybroOdoo** [comment]
Hello
We can definitely do the customization if you require as per your need. Please contact our marketing person for the same(Mail ID: asst.bd@cybrosys.com).
