### ISSUE TITLE
V10 Stock Transport Management - Option to entry transport via or vehicle ID in Picking Form Instead of sales form

### ISSUE THREAD

**Issue by bunhin** [CybroOdoo/CybroAddons#65]
Please inform how to be able entry transport vehicle in the picking form as well.  The transport vehicle ID is not possible to be determined in sales order stage (when there is time gap between sale order confirm and delivery time), IMHO it is better to put entry of transport vehicle id in the picking form, rather tahn in the sales order form. Or on both form can entry it

thank you

**Comment by sreejithcybrosys** [comment]
Thanks for your suggestions, we will look into that. If you have any suggestions/additional needs please contact us at odoo@cybrosys.com
