### ISSUE TITLE
Error al instalar developer_mode

### ISSUE THREAD

**Issue by pedroortega-punt** [CybroOdoo/CybroAddons#71]
Buenos días, 

He intentado instalar el módulo developer_mode y sale el siguiente error.

![imagen](https://user-images.githubusercontent.com/18347857/39676443-1af12ba4-516b-11e8-92ce-9ba44ecf08f9.png)

**Comment by pedroortega-punt** [comment]
Me podéis ayudar?

Gracias.

**Comment by CybroOdoo** [comment]
We tested here and we couldn't find this issue. It may be your other custom modules issue.
Hint: "base.model_view_kanban" may override by any other module. So you can check with new DB.
