### ISSUE TITLE
Error al instalar developer_mode

### ISSUE THREAD

**Issue by pedroortega-punt** [CybroOdoo/CybroAddons#73]
Good Morning,

I created a new bbdd without installing any other module, and I installed yours and it still does not work, I get the same error.

There is no custom module in the bbdd.

Any suggestions?

![imagen](https://user-images.githubusercontent.com/18347857/39814996-e8717ee4-5396-11e8-9029-c4749625fd6f.png)

**Comment by CybroOdoo** [comment]
Please provide us your odoo10 version. We can't reproduce this error.

**Comment by pedroortega-punt** [comment]
Good Morning.

This is the version.

commit 756571749e7ebb5049fd1a1eb6d170429bed0623
Author: OCA Git Bot <oca-git-bot@odoo-community.org>
Date:   Tue Feb 27 00:31:13 2018 +0100
Merge remote-tracking branch 'odoo/10.0' into 10.0

Versión community without enterprise.

**Comment by CybroOdoo** [comment]
Hi,
Please  update your odoo10 version to the latest.
