### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Vartkat** [CybroOdoo/CybroAddons#8]
Hello and congrats for this module.

As far as I tested your module I see that it changes all amounts lines as if I have done it by hand. 
Is it possible to add a subtotal option, i.e. no line modification, the client sees the real price on each line, then, down, the total before discount, discount, taxes and final Total.

<img width="612" alt="no line mod option" src="https://cloud.githubusercontent.com/assets/1696899/23399448/83eeac82-fda0-11e6-843f-6facfc419e71.png">

**Comment by CybroOdoo** [comment]
Hello,

Thanks for your suggestion. This module is just an upgradation of our
version 8 module. So we didn't add anything extra. We can definitely do the
customization if you require as per your need. Please contact our marketing
person for the same(Mail ID: asst.bd@cybrosys.com).

With Regards,
Cybrosys Odoo Team
