### ISSUE TITLE
[10.0] Website_Coupon => Please check the voucher value

### ISSUE THREAD

**Issue by Boss1669** [CybroOdoo/CybroAddons#80]
[10.0] Website_Coupon => Please check the voucher value
Not Sure why this occur
![capture](https://user-images.githubusercontent.com/26357404/40794601-de2d5238-6529-11e8-828c-3f09a9fb1250.JPG)

**Comment by lintocybrosys** [comment]
Hi Boss1669, 
This is not an error. There is a maximum value and minimum value for each voucher. When you create the coupons, it's value should be in between the maximum and minimum values of the related voucher. Otherwise it will create a warning like this, asking you to check the voucher values.
