### ISSUE TITLE
[11.0][import_product_image] Missing in 11.0 branch

### ISSUE THREAD

**Issue by SalahAdDin** [CybroOdoo/CybroAddons#85]
Hi

I found this app here: https://www.odoo.com/apps/modules/11.0/import_product_image/

But i'm trying to find in this repo and i cannot. It is in `10.0` branch but not in `11.0`.

Is anyone playing to upgrade this?

Thank you.

**Comment by CybroOdoo** [comment]
Hi SalahAdDin,
This module has a python3 compatible issue. We raised a ticket to remove the module from the apps, but it is not removed yet. Also, we are trying to make package compatible with python3. Hope we can update it soon.

Thanks!

**Comment by SalahAdDin** [comment]
@CybroOdoo Thank you very much.

**Comment by SalahAdDin** [comment]
@CybroOdoo , any plans to port this module to **Odoo** `11.0`.
