### ISSUE TITLE
[11.0][developer_mode]Missing version label

### ISSUE THREAD

**Issue by SalahAdDin** [CybroOdoo/CybroAddons#91]
This module works like a charm, but with custom backend's theme, the version label isn't shown:
![faltaversion](https://user-images.githubusercontent.com/5034215/44152185-8603048a-a0ad-11e8-9cdf-06fed3df8654.png)

I'm using this theme: https://github.com/Openworx/backend_theme

**Comment by CybroOdoo** [comment]
Sorry for the delayed response, All Cybrosys modules are tested with basic Odoo. We cannot assure you how it will behave with other customs apps since we can't predict what will be the customer using along with this apps.
