### ISSUE TITLE
product_price_update_adcanced

### ISSUE THREAD

**Issue by gr22** [CybroOdoo/CybroAddons#93]
1. the fields for price and cost in the wizard are integer so it rounds all of the prices. It should be Float i would say as in product_template.

2. If you have 2 products with the same name it fails with: "expecting singleton".  This is expected since 
`prod_obj =  self.env['product.template'].search([('name', '=', self.name.name)]) `
can return multiple values and then 
`self.sale_price = prod_obj.list_price fails`

**Comment by CybroOdoo** [comment]
Thanks for reaching us!

We have updated the module.
