### ISSUE TITLE
Decimal Precision

### ISSUE THREAD

**Issue by hevxpr** [CybroOdoo/CybroAddons#99]
After install sale_discount_total, decimal in discount field of vendor bills become 0.00000000000000000000.

**Comment by tglukhov** [comment]
Hello everyone, 

This module is really nice but i have the same issue as hevwpr: 

while creating order lines in quotations i have a discount with 20 zeros after comma.
if i write 2.56 it autocomplete the field with 2.56000000000000138556
if i print this quotation, it seems to print only 2 numbers after comma like we need.

however in invoice if i chose a 3.27 % discount it will display 3.27000000000000046185 in the printed invoice(it displays the same when i click in order line) 
see the screenshots below 

i work with odoo V10
![screenshot from 2019-01-04 11-04-12](https://user-images.githubusercontent.com/45606959/50711155-5353cc80-1011-11e9-9f27-63dbd6d1e7a0.png)
![screenshot from 2019-01-04 11-04-27](https://user-images.githubusercontent.com/45606959/50711167-5fd82500-1011-11e9-9b01-7899de5c08a5.png)

**Comment by tglukhov** [comment]
i checked the code and found this: 
 in the sale.py 
```
class SaleOrderLine(models.Model):
    _inherit = "sale.order.line"

    discount = fields.Float(string='Discount (%)', digits=(16, 20), default=0.0)

```
and in account_invoice.py 
```
class AccountInvoiceLine(models.Model):
    _inherit = "account.invoice.line"

    discount = fields.Float(string='Discount (%)', digits=(16, 20), default=0.0)
```
why dou you use `digits=(16, 20)` in order to use `digits=dp.get_precision('Discount') `?

i tried to change 20 to 2 and everything is going good, there is no more problem with decimals.
